### ISSUE TITLE
Upgrade ESLint and copy latest activity-stream rules?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/loci#31]
We (well, @Mardak) have been making oodles of changes to our [**mozilla/activity-stream** .eslintrc](https://github.com/mozilla/activity-stream/blob/master/.eslintrc) config file lately. Not sure if you kids want to copy-pasta those (and bump any ESLint-related devDeps) so it'll be easier to merge this back into activity-stream repo at some point in the future.

I haven't dared sync to master and copy/paste rules yet to see how many of the errors/warnings are auto-fixable by ESLint, but hopefully not too Herculean of a task.

**Comment by rittme** [comment]
I'm working on this as we want to migrate the worker queue part of the add-on to Activity Stream.
